openapi: 3.0.1
info:
  title: API contract for financial accelerator extension points in WSO2 IS
  description: This API defines the REST API contract for services that implements logic to extend the Open Data accelerator flow.
  contact:
    name: WSO2
    url: https://wso2.com/solutions/financial-services/open-banking/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: v1.0.0-M4
servers:
- url: https://virtserver.swaggerhub.com/wso2-f5b/OB4/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- BasicAuth: []
- OAuth2: []
tags:
- name: Client Registration
  description: APIs for dynamic client registration flow extensions
- name: Consent
  description: APIs for consent flow extensions
- name: Token
  description: APIs for token flow extensions
- name: Authorize
  description: APIs for authorize flow extensions
- name: Token & Authorize
  description: APIs for token & authorize flow extensions
- name: Error Handling
  description: APIs for handling accelerator errors
paths:
  /error-mapper:
    post:
      tags:
      - Error Handling
      summary: map accelerator level error formats to custom error formats
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorMapperRequestBody'
            example:
              requestId: Ec1wMjmiG8
              data: 
                error:
                    code: "401"
                    description: Invalid client ID provided.
                    operation: consent_create
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForErrorMapper'
              example:
                responseId: Ec1wMjmiG8
                data: 
                  customErrorCode: invalid
                  customErrorDescription: Invalid client ID provided. 
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                errorMessage: invalid_request
                errorDescription: Data is missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                errorMessage: server_error
                errorDescription: Failed to process the response

  /pre-dynamic-client-registration:
    post:
      tags:
      - Client Registration
      summary: handle pre validations & define data to store in dynamic client registration step
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppCreationValidationRequestBody'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForDcrValidation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Data is missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
              
  /pre-dynamic-client-update:
    post:
      tags:
      - Client Registration
      summary: handle pre validations & define data to store in dynamic client update step
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppUpdateValidationRequestBody'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForDcrUpdate'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Data is missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /pre-consent-generation:
    post:
      tags:
      - Consent
      summary: handle pre-consent generation validations & storing consent data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentCreationRequestBody'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForConsentCreation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                data:
                  errorMessage: invalid_request
                  errorDescription: Data is missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /post-consent-generation:
    post:
      tags:
      - Consent
      summary: "handle post-consent generation -response generation,validations"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentPostCreationRequestBody'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForResponseAlternation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Data is missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /pre-consent-retrieval:
    post:
      tags:
      - Consent
      summary: handle pre-consent retrieval validations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentRetrievalRequestBody'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForResponseAlternation'
             
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Data is missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
 
  /pre-consent-revocation:
    post:
      tags:
      - Consent
      summary: handle pre-consent revocation validations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentRevocationRequestBody'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForConsentRevocation'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Data is missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /pre-consent-authorization:
    post:
      tags:
      - Consent
      summary: handle validations before consent  authorization and consent data to load in consent authorization UI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentAuthorizationRequestBody'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForPreConsentAuthorization'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Permissions are missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /consent-validation:
    post:
      tags:
      - Consent
      summary: handle custom consent data validations before data access
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentValidationRequestBody'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
              examples:
                successExample:
                  summary: Success response
                  value:
                    responseId: Ec1wMjmiG8
                    status: SUCCESS
                failedExample:
                  summary: Failed response
                  value:
                    status: ERROR
                    errorCode: 401
                    errorMessage: invalid_permissions
                    erroreDescription: "The requested  permissions are invalid, unknown"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Permissions are missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /pre-access-token-generation:
    post:
      tags:
      - Token
      summary: Handles pre-token generation requests
      operationId: preTokenGeneration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreAccessTokenGenerationRequestBody'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForTokenGeneration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Permissions are missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                xtatus: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /pre-user-authorization:
    post:
      tags:
      - Authorize
      summary: Handles pre-user authorization requests
      operationId: preUserAuthorization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreUserAuthorizationRequestBody'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
              examples:
                successExample:
                  summary: Success response
                  value:
                    responseId: Ec1wMjmiG8
                    status: SUCCESS
                failedExample:
                  summary: Failed response
                  value:
                    status: ERROR
                    errorCode: 401
                    errorMessage: invalid_permissions
                    erroreDescription: "The requested  permissions are invalid, unknown"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Permissions are missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /post-user-authorization:
    post:
      tags:
      - Authorize
      summary: Handles post-user authorization requests
      operationId: postUserAuthorization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserAuthorizationBody'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForPostUserAuthorization'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: invalid_request
                errorDescription: Permissions are missing
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                responseId: Ec1wMjmiG8
                status: ERROR
                errorMessage: server_error
                errorDescription: Failed to process the response
  /pre-id-token-generation:
    post:
      tags:
      - Token & Authorize
      summary: Handles additional claims for ID token
      operationId: idTokenAdditionalClaims
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreIdtokenGenerationBody'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200ForIdtokenGeneration'
components:
  schemas:
    Response200ForErrorMapper:
      type: object
      properties:
        responseId:
          type: string
        data:
          type: object  
          description: Defines the custom error response.
  
    Response200ForDcrValidation:
      oneOf:
      - $ref: '#/components/schemas/SuccessResponseDCRValidation'
      - $ref: '#/components/schemas/FailedResponseDCRValidation'
      
    Response200ForDcrUpdate:
      oneOf:
      - $ref: '#/components/schemas/SuccessResponseDCRUpdate'
      - $ref: '#/components/schemas/FailedResponseDCRValidation'
      
    ErrorMapperRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: A unique correlation identifier
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/ErrorMapperData'
    
    AppCreationValidationRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: A unique correlation identifier
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/AppCreationValidationData'
          
    ErrorMapperData:
      type: object
      description: Defines the context data related to the errors.
      properties:
        error:
          $ref: '#/components/schemas/Error'
            
    Error:
      type: object
      description: Defines an error object with details.
      properties:
        code:
          type: string
          description: Error code identifying the specific issue.
        description:
          type: string
          description: Detailed description of the error.
        operation:
          type: string
          description: The operation where the error occurred.
          
    AppCreationValidationData:
      type: object
      description: Defines the context data related to the app creation validation.
      properties:
        clientRegistration:
          type: object
          description: DCR registration request
        softwareStatement:
          type: object
          description: Parameters of the decoded SSA.
    AppUpdateValidationRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: A unique correlation identifier
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/AppUpdateValidationData'
          
    AppUpdateValidationData:
      type: object
      description: Defines the context data related to the app creation validation.
      properties:
        clientUpdate:
          type: object
          description: DCR registration request
        softwareStatement:
          type: object
          description: Parameters of the decoded SSA.
        clientAppProperties:
          type: object
          description: properties of the existing client application.
    
    SuccessResponseDCRValidation:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        data:
          type: object  
          description: Defines the success response.
          properties:
            attributesToStore:
              type: object
              
    SuccessResponseDCRUpdate:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        data:
          type: object  
          description: Defines the success response.
          properties:
            attributesToUpdate:
              type: object      
    
    FailedResponseDCRValidation:
      required:
      - errorDescription
      - errorMessage
      - status
      type: object
      properties:
        status:
          type: string
          description: "Indicates the outcome of the request. For a failed operation, this should be set to ERROR."
          enum:
          - ERROR
        errorCode:
          type: string
          description: If any custom error code to return.
        errorMessage:
          type: string
          description: Provides the reason for error.
        errorDescription:
          type: string
          description: Offers a detailed explanation of the error.
    
    RequestBase:
      type: object
      properties:
        requestId:
          type: string
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/RequestBaseData'
    AdditionalClaimsTokenRequest:
      allOf:
      - $ref: '#/components/schemas/RequestBase'
      - type: object
        properties:
          operation:
            type: string
            example: additionalIdTokenClaimsTokenResponse
    AdditionalClaimsAuthzRequest:
      allOf:
      - $ref: '#/components/schemas/RequestBase'
      - type: object
        properties:
          operation:
            type: string
            example: additionalIdTokenClaimsAuthzResponse
    ResponseBase:
      type: object
      properties:
        responseId:
          type: string
          example: Ec1wMjmiG8
        status:
          type: string
          example: SUCCESS
        data:
          $ref: '#/components/schemas/ResponseBaseData'
    AdditionalClaimsTokenResponse:
      allOf:
      - $ref: '#/components/schemas/ResponseBase'
      - type: object
       
          
    AdditionalClaimsAuthzResponse:
      allOf:
      - $ref: '#/components/schemas/ResponseBase'
      - type: object
        
    PostUserAuthRequestBase:
      type: object
      properties:
        requestId:
          type: string
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/PostUserAuthRequestBaseData'
    PostUserAuthRefreshTokenRequest:
      allOf:
      - $ref: '#/components/schemas/PostUserAuthRequestBase'
      - type: object
        properties:
          operation:
            type: string
            example: getRefreshTokenValidityPeriod
    PostUserAuthApprovedScopesRequest:
      allOf:
      - $ref: '#/components/schemas/PostUserAuthRequestBase'
      - type: object
        properties:
          operation:
            type: string
            example: getApprovedScopes
    PostUserAuthResponseBase:
      type: object
      properties:
        responseId:
          type: string
          example: Ec1wMjmiG8
        status:
          type: string
          enum:
          - SUCCESS
    PostUserAuthRefreshTokenResponse:
      allOf:
      - $ref: '#/components/schemas/PostUserAuthResponseBase'
      - type: object
        properties:
          data:
            $ref: '#/components/schemas/PostUserAuthRefreshTokenResponseData'
          
    PostUserAuthApprovedScopesResponse:
      allOf:
      - $ref: '#/components/schemas/PostUserAuthResponseBase'
      - type: object
        properties:
          data:
            $ref: '#/components/schemas/PostUserAuthApprovedScopesResponseData'
    Request:
      type: object
      properties:
        consentPayload:
          type: object
          description: The receipt used by Third parties which includes detailed information on data access request
        resourcePath:
          type: string
          description: To identify requested consent type
    RequestForPostConsentCreation:
      type: object
      properties:
        consentId:
          type: string
          description: To identify requested
        consentResource:
          type: object
          description: detailed consent resource 
        resourcePath:
          type: string
          description: consent resource path 
    ConsentRetrievalData:
      type: object
      properties:
        consentId:
          type: string
          description: The consent id
        consentResource:
          type: object
          description: The  consent resource containing receipt,attributes
        resourcePath:
          type: string
          description: Resource url
    ConsentAuthorizationData:
      type: object
      properties:
        consentId:
          type: string
          example: An UUID
        userId:
          type: string
          example: Username
        consentResource:
          type: object
          description: Detailed consent resource
    ConsentValidationData:
      type: object
      properties:
        consentId:
          type: string
          description: The consent id
        consentResource:
          type: object
          description: The detailed consent resource
        dataPayload:
          type: object
          description: The receipt used by Third parties which includes detailed information on data access request
        consentType:
          type: string
          description: Consent Type -account/payment/cof
    SuccessResponse:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        
    SuccessResponseTokenGeneration:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        data:
          $ref: '#/components/schemas/SuccessResponseTokenGenerationData'
          
    SuccessResponseIssueRefreshTokenGeneration:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        data:
          $ref: '#/components/schemas/SuccessResponseIssueRefreshTokenGenerationData'

    SuccessResponseConsentRevocation:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        data:
          $ref: '#/components/schemas/SuccessResponseConsentRevocationData'
    SuccessResponsePreConsentAuthorization:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        data:
          $ref: '#/components/schemas/SuccessResponsePreConsentAuthorizationData'
    SuccessResponseForResponseAlternation:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        data:
          $ref: '#/components/schemas/SuccessResponseForResponseAlternationData'
    SuccessResponsePreConsentGeneration:
      type: object
      properties:
        responseId:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
        data:
          $ref: '#/components/schemas/SuccessResponsePreConsentGenerationData'
    FailedResponse:
      required:
      - data
      - status
      - errorCode
      type: object
      properties:
        status:
          type: string
          description: "Indicates the outcome of the request. For a failed operation, this should be set to ERROR."
          enum:
          - ERROR
        errorCode:
          type: integer
          description: If any custom error code to return.
        data:
          type: object
          description: :"Custom error object to response back"
    
    FailedResponseInConsent:
      required:
      - data
      - status
      - errorCode
      type: object
      properties:
        status:
          type: string
          description: "Indicates the outcome of the request. For a failed operation, this should be set to ERROR."
          enum:
          - ERROR
        errorCode:
          type: integer
          description: If any custom error code to return.
        data:
          type: object
          description: :"Custom error object to response back"
    ErrorResponse:
      type: object
      required:
      - data
      - status
      properties:
        status:
          type: string
          description: "Indicates the outcome of the request. For an error operation, this should be set to ERROR."
          enum:
          - ERROR
        data:
          type: object
          description: :"Custom error object to response back"
    ConsentCreationRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: A unique correlation identifier
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/Request'
    ConsentPostCreationRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: A unique correlation identifier
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/RequestForPostConsentCreation'
    ConsentRetrievalRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: A unique correlation identifier
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/ConsentRetrievalData'
    ConsentRevocationRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: A unique correlation identifier
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/ConsentRetrievalData'
    ConsentAuthorizationRequestBody:
      type: object
      properties:
        requestId:
          type: string
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/ConsentAuthorizationData'
    ConsentValidationRequestBody:
      type: object
      properties:
        requestId:
          type: string
          description: A unique correlation identifier
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/ConsentValidationData'
    AccessTokenGenerationRequestBody:
      type: object
      properties:
        scopes:
          type: array
          example:
          - accounts
          - payments
          - consentId
          items:
            type: string
        grantType:
          type: string
          example: authorization_code
    AccessTokenGenerationRequestBodyForRefresh:
      type: object
      properties:
        grantType:
          type: string
          example: authorization_code
    PreAccessTokenGenerationRequestBody:
      oneOf:
      - type: object
        properties:
          requestId:
            type: string
            example: Ec1wMjmiG8
          data:
            $ref: '#/components/schemas/AccessTokenGenerationRequestBody'
          operation:
            type: string
            example: appendParametersToTokenResponse
      - type: object
        properties:
          requestId:
            type: string
            example: Ec1wMjmiG8
          request:
            $ref: '#/components/schemas/AccessTokenGenerationRequestBodyForRefresh'
          operation:
            type: string
            example: issueRefreshToken
    PreUserAuthorizationRequestBody:
      type: object
      properties:
        requestId:
          type: string
          example: Ec1wMjmiG8
        data:
          $ref: '#/components/schemas/PreUserAuthorizationRequestBodyData'
    Response200ForConsentCreation:
      oneOf:
      - $ref: '#/components/schemas/SuccessResponsePreConsentGeneration'
      - $ref: '#/components/schemas/FailedResponseInConsent'
    Response200ForResponseAlternation:
      oneOf:
      - $ref: '#/components/schemas/SuccessResponseForResponseAlternation'
      - $ref: '#/components/schemas/FailedResponseInConsent'
    Response200:
      oneOf:
      - $ref: '#/components/schemas/SuccessResponse'
      - $ref: '#/components/schemas/FailedResponse'
    Response200ForConsentRevocation:
      oneOf:
      - $ref: '#/components/schemas/SuccessResponseConsentRevocation'
      - $ref: '#/components/schemas/FailedResponse'
    Response200ForPreConsentAuthorization:
      oneOf:
      - $ref: '#/components/schemas/SuccessResponsePreConsentAuthorization'
      - $ref: '#/components/schemas/FailedResponse'
    Response200ForTokenGeneration:
      oneOf:
      - $ref: '#/components/schemas/SuccessResponseTokenGeneration'
      - $ref: '#/components/schemas/SuccessResponseIssueRefreshTokenGeneration'
      - $ref: '#/components/schemas/FailedResponse'
    PostUserAuthorizationBody:
      oneOf:
      - $ref: '#/components/schemas/PostUserAuthRefreshTokenRequest'
      - $ref: '#/components/schemas/PostUserAuthApprovedScopesRequest'
    Response200ForPostUserAuthorization:
      oneOf:
      - $ref: '#/components/schemas/PostUserAuthRefreshTokenResponse'
      - $ref: '#/components/schemas/PostUserAuthApprovedScopesResponse'
      - $ref: '#/components/schemas/FailedResponse'
    PreIdtokenGenerationBody:
      oneOf:
      - $ref: '#/components/schemas/AdditionalClaimsTokenRequest'
      - $ref: '#/components/schemas/AdditionalClaimsAuthzRequest'
    Response200ForIdtokenGeneration:
      oneOf:
      - $ref: '#/components/schemas/AdditionalClaimsTokenResponse'
      - $ref: '#/components/schemas/AdditionalClaimsAuthzResponse'
      - $ref: '#/components/schemas/FailedResponse'
    RequestBaseData:
      type: object
      properties:
        userId:
          type: string
          example: ben@wso2.com
        consentId:
          type: string
          example: "123"
    ResponseBase_data_claims:
      type: object
      properties:
        key:
          type: string
          example: claim1
        value:
          type: string
          example: "123"
    ResponseBaseData:
      type: object
      properties:
        claims:
          type: array
          example:
          - key: claim1
            value: "123"
          - key: claim2
            value: "456"
          items:
            $ref: '#/components/schemas/ResponseBase_data_claims'
    PostUserAuthRequestBaseData:
      type: object
      properties:
        scopes:
          type: array
          example:
          - accounts
          - payments
          items:
            type: string
        consentId:
          type: string
          example: "123"
        validityPeriod:
          type: integer
          example: 1000
    PostUserAuthRefreshTokenResponseData:
      type: object
      properties:
        refreshTokenValidityPeriod:
          type: integer
          example: 1000
    PostUserAuthApprovedScopesResponseData:
      type: object
      properties:
        approvedScopes:
          type: array
          example:
          - accounts
          - payments
          - consentId
          items:
            type: string
    SuccessResponseTokenGenerationDataParameters:
      type: object
      properties:
        key:
          type: string
          example: consent-id
        value:
          type: string
          example: "123"
    SuccessResponseTokenGenerationData:
      type: object
      properties:
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/SuccessResponseTokenGenerationDataParameters'
    SuccessResponseIssueRefreshTokenGenerationData:
      type: object
      properties:
        issueRefreshToken:
          type: boolean
    SuccessResponseConsentRevocationData:
      type: object
      properties:
        revocationStatusName:
          type: string
          description: Name for the revoked status
        requireTokenRevocation:
          type: string
          description: Require access token to be revoked
    SuccessResponsePreConsentAuthorizationData:
      type: object
      properties:
        consentData:
          type: object
          description: consent data to be populated on consent grant UI
        consumerData:
          type: object
          description: Data provider's backend data
    SuccessResponseForResponseAlternationData:
      type: object
      properties:
        responseData:
          type: object
          description: Generated custom response body
    SuccessResponsePreConsentGenerationData:
      type: object
      properties:
        consentType:
          type: string
          description: Type of consent -account/payment
        consentStatus:
          type: string
          description: status of the consent
        validityTime:
          type: integer
          description: validity time of the consent
          format: int64
        recurringIndicator:
          type: boolean
          description: if consent is recurring
        consentFrequency:
          type: integer
          description: frequency of consent access
        consentPayload:
          type: object
          description: Modified consent receipt
    PreUserAuthorizationRequestBodyData:
      type: object
      description: full request object
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://example.com/oauth/token
          scopes:
            process: process request generate response